"""empty message

Revision ID: 2b3696c7bff6
Revises: 6ac1d31a2f56
Create Date: 2024-09-07 16:19:28.121204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b3696c7bff6'
down_revision = '6ac1d31a2f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('discipline_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('discipline_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
