"""empty message

Revision ID: 2f548d610860
Revises: 565131e12b04
Create Date: 2024-09-09 15:56:57.997898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f548d610860'
down_revision = '565131e12b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('kal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kal', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
