"""empty message

Revision ID: 5124ae7554cc
Revises: 01739dd96348
Create Date: 2024-09-06 19:07:20.968212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5124ae7554cc'
down_revision = '01739dd96348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('room')

    # ### end Alembic commands ###
