"""empty message

Revision ID: 565131e12b04
Revises: 2b3696c7bff6
Create Date: 2024-09-08 13:52:29.387783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565131e12b04'
down_revision = '2b3696c7bff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('job')

    # ### end Alembic commands ###
