"""empty message

Revision ID: 616e39814def
Revises: 70fabd77ae1b
Create Date: 2024-09-13 16:12:57.221548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616e39814def'
down_revision = '70fabd77ae1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplines', schema=None) as batch_op:
        batch_op.alter_column('kal',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplines', schema=None) as batch_op:
        batch_op.alter_column('kal',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
