"""empty message

Revision ID: 648dc498d07d
Revises: 2f548d610860
Create Date: 2024-09-11 09:43:43.706453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648dc498d07d'
down_revision = '2f548d610860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
