"""empty message

Revision ID: 70fabd77ae1b
Revises: 648dc498d07d
Create Date: 2024-09-13 16:10:37.865884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fabd77ae1b'
down_revision = '648dc498d07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplines', schema=None) as batch_op:
        batch_op.drop_column('kal')

    # ### end Alembic commands ###
