"""empty message

Revision ID: fca25206cfc7
Revises: 8607a7106fc0
Create Date: 2024-09-07 12:27:02.743102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca25206cfc7'
down_revision = '8607a7106fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplines', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
